---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g bower yarn
  - bower --version
  - yarn --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - npm test

#after_success:
#  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < coverage/lcov.info
#
#env:
#  - COVERAGE=true CODECLIMATE_REPO_TOKEN=2018541b189c3edb927aac5eb867ba14606840df1c10234894af8b535f4cd519
